# -*- coding: utf-8 -*-
"""Campo_de_velocidades

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SYiTIgab-IYAFmNdbvn_Q0tdJ91oFi84
"""

import numpy as np
import matplotlib.pyplot as plt

def funt(x,y):
  return (2*x*(1-(4/(x*2+y*2))))
def dx(f,x,y,h):
  return (funt(x+h,y)-funt(x-h,y))/(2*h)
def dy(f,x,y,h):
  return (funt(x,y+h)-funt(x,y-h))/(2*h)

n = 25
x = np.linspace(-4,4,n)
y = np.linspace(-4,4,n)

def Campo(x,y):
    h = 0.001
    Ex = np.zeros((n,n))
    Ey = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            if (x[i]**2 + y[j]**2) > 4:
                Ex[i,j] = dx(funt,x[i],y[j],h)
                Ey[i,j] = dy(funt,x[i],y[j],h)
    
    return Ex,Ey

fig = plt.figure(figsize=(5,5))
ax = fig.add_subplot()

Ex, Ey = Campo(x,y)

for i in range(n):
    for j in range(n):
        ax.quiver(x[i],y[j],Ex[i,j],Ey[i,j], color='r')


ax.plot(2*np.cos(np.linspace(0, 2*np.pi)), 2*np.sin(np.linspace(0, 2*np.pi)))
ax.set_xlabel("x [cm]")
ax.set_ylabel("y [cm]")